Repository FlamingoFiestaStudio/OlympusGoneWild, pull requests merged in 2023-09, with the labels that each got.

#30 Adds sprite for player idle animation
  assets/Apolo/IdleAnimationSprite.png
Labels: art

#29 Added pause menu
  UI/pause_menu.gd
  UI/pause_menu.tscn
  assets/Apolo/IdleAnimationSprite.png.import
Labels: enhancement

#37 Update README.md
  README.md
Labels: documentation

#39 Add wiki and action to autodeploy wiki
  .github/workflows/DeployWiki.yml
  wiki/ArtAndStyle.md
  wiki/GameMechanics.md
  wiki/History.md
  wiki/Home.md
  wiki/_Footer.md
  wiki/images/Enemy1.jpeg
  wiki/images/Enemy2.jpeg
  wiki/images/Player.png
Labels: documentation
