Repository FlamingoFiestaStudio/OlympusGoneWild, pull requests merged in 2023-10, with the labels that each got.

#52 Organized file structure
  Player/Player.tscn
  Player/sprites/idle/player-idle-1.png.import
  Player/sprites/idle/player-idle-2.png.import
  Player/sprites/idle/player-idle-3.png.import
  Player/sprites/idle/player-idle-4.png.import
  Player/sprites/run/player-run-1.png.import
  Player/sprites/run/player-run-2.png.import
  Player/sprites/run/player-run-3.png.import
  Player/sprites/run/player-run-4.png.import
  Player/sprites/run/player-run-5.png.import
  Player/sprites/run/player-run-6.png.import
  icon.svg
  icon.svg.import
  main/level_1.tscn
  menus/menu.gd
  menus/menu.tscn
  menus/pause_menu.gd
  menus/pause_menu.tscn
  project.godot
  wiki/.gdignore
Labels: P1

#96 fix(tilemap): camera limits
  main/level_1.gd
  main/level_1.tscn
  map/tile_map.tscn
Labels: bug, programming, P2

#97 Added the CONTRIBUTING file and updated the ProjectBestPractices
  .github/CONTRIBUTING.md
  wiki/ProjectBestPractices.md
Labels: documentation

#103 Docs: Added templates issues
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/dev-issue.md
  .github/ISSUE_TEMPLATE/feature-request.md
  README.md
Labels: documentation

#105 Add documentation to report a security breach
  .github/ISSUE_TEMPLATE/security-vulnerability-report.md
  SECURITY.md
Labels: documentation

#113 docs: remove security issue template
  .github/ISSUE_TEMPLATE/security-vulnerability-report.md
  SECURITY.md
Labels: documentation
