Repository FlamingoFiestaStudio/OlympusGoneWild, pull requests merged in 2023-11, with the labels that each got.

#119 chore: Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#118 Bump Godot version to 4.1.3
  README.md
  project.godot
  wiki/Home.md
Labels: enhancement

#116 Player shooting system
  bullets/bullet.gd
  bullets/bullet.tscn
  bullets/sprites/icon.png
  bullets/sprites/icon.png.import
  main/level_1.gd
  main/level_1.tscn
  map/tile_map.tscn
  player/Player.gd
  player/Player.tscn
  player/Weapon.gd
  project.godot
Labels: enhancement

#120 Enemy setup
  enemies/Enemy.tscn
  main/level_1.gd
  main/level_1.tscn
Labels: enhancement

#123 Fix documentation Godot version
  README.md
  wiki/Home.md
Labels: documentation

#124 Removed unused variables and nodes
  player/Player.gd
  player/Player.tscn
  player/Weapon.gd
Labels: enhancement

#125 Added preview images to Art and Style wiki page
  wiki/ArtAndStyle.md
  wiki/images/Enemy1.jpeg
  wiki/images/Enemy2.jpeg
  wiki/images/EnemySkeletonAttacking.gif
  wiki/images/EnemySkeletonDeath.gif
  wiki/images/EnemySkeletonHit.gif
  wiki/images/EnemySkeletonRunning.gif
  wiki/images/Player.png
  wiki/images/PlayerAttacking.gif
  wiki/images/PlayerIdle.gif
  wiki/images/PlayerRun.gif
  wiki/images/UIMainMenu.jpeg
  wiki/images/UIOptionsMenu.png
  wiki/images/UIOptionsScreenMenu.png
  wiki/images/UIOptionsSoundMenu.png
  wiki/images/UIPauseMenu.jpeg
Labels: Documentation📝

#131 feat(enemy): enemy movement set up
  .gitignore
  enemies/Enemy.gd
  enemies/Enemy.tscn
  main/level_1.gd
  map/tile_map.tscn
  player/Player.gd
Labels: enhancement

#137 Enemy attack system setup
  enemies/Enemy.gd
  enemies/Enemy.tscn
  main/level_1.gd
  player/Player.gd
  player/Player.tscn
  player/Weapon.gd
Labels: enhancement, Core ⚙️
